services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=production
      - VITE_APP_BACKEND_URL=http://server:5000
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017
      - MONGO_USER=root
      - MONGO_PASS=rootpassword
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: mydatabase
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: mydatabase
      DB_PORT: 27017
    volumes:
      - ./mongo/data:/data/db